version: '3.0'
services:
  flask:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Project:/Project
      - ./uploads:/uploads
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000
  # jupyterlab:
  #   build:
  #     context: ./Docker
  #     dockerfile: Dockerfile-opencv
  #   container_name: kaggle_jupyter
  #   ports:
  #     - "88:8888"
  #   volumes:
  #     - ./Project:/Project # ← notebookをホストと共有したいためディレクトリをマウント
  #   command: jupyter lab --allow-root --NotebookApp.token=''

  # jupyterlab:
  #   image: jupyter/datascience-notebook:latest  
  #   container_name: jupyterlab  
  #   environment:  
  #     TZ: "Asia/Tokyo"  
  #     JUPYTER_ENABLE_LAB: "yes"  
  #   ports:  
  #     - "88:8888"  
  #   volumes:  
  #     - ./Project:/Project
  #   command: jupyter lab --allow-root --NotebookApp.token=''