version: '3.0'
services:
  flask:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Project:/Project
      - ./uploads:/uploads
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000
  jupyterlab:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    container_name: jphack_jupyter
    ports:
      - "80:8888"
    volumes:
      - ./Project:/Project # ← notebookをホストと共有したいためディレクトリをマウント
    command: jupyter lab --allow-root --NotebookApp.token=''